# Data options
bootstrap: false
data_dir: online_voltage
fourier_features: true

# Model/ensemble options
model_name: null
ensemble: 0
ensemble_name: null

# Training hyperparamters
iterations: 2500
lr: 0.01
display_every: 250
model_type: "ResOrthoONet"
batch_size: 512
online: true

# Layer sizes
# Note: For overrides, enter layers as layers=10,10 not layers=[10, 10]
layers: [10, 10, 10, 10]

# Scheduler
decay_gamma: 0.998
minimum_lr: 0.003

verbose: true