# Data options
bootstrap: false
data_dir: advection
fourier_features: false

# Model/ensemble options
model_name: null
ensemble: 0
ensemble_name: null

# Training hyperparamters
iterations: 30000
lr: 0.0005
display_every: 250
model_type: "ResOrthoONet"
batch_size: null

# Layer sizes
# Note: For overrides, enter layers as layers=10,10 not layers=[10, 10]
layers: [20, 20, 20, 20, 20]

# Scheduler
decay_gamma: null
minimum_lr: null

verbose: False